[project]
name = "doa-py"
version = "0.1.0"
description = "DOA estimation algorithms implemented in Python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cvxpy>=1.5.3",
    "matplotlib>=3.9.2",
    "numpy>=2.1.1",
    "scikit-image>=0.24.0",
    "scipy>=1.14.1",
]
